apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache2-deployment
spec:
  selector:
    matchLabels:
      app: apache2
  replicas: 3
  template:
    metadata:
      labels:
        app: apache2
    spec:
      containers:
      - name: apache2
        image: httpd:2.4
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: apache2-service
spec:
  selector:
    app: apache2
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
